default_platform :ios

platform :ios do
  ####### Testing #######

    desc "Runs all the tests"
    lane :tests do
      unit_tests
    end

    desc "Runs all unit tests"
    lane :unit_tests do
      scan(
        workspace: "FBSnapshotTestCaseDemo.xcworkspace",
        scheme: "FBSnapshotTestCaseDemo",
        devices: ["iPhone 8"]
      )
    end

    desc "Runs all ui tests"
    lane :ui_tests do
      scan(
        workspace: "FBSnapshotTestCaseDemo.xcworkspace",
        scheme: "FBSnapshotTestCaseDemo",
        devices: ["iPhone 8"],
        clean: true
      )
    end

end
